In [1]:
# marks=[88,90,30,45,75]
# new_marks = [mark + 5 for mark in marks]
# # print(" marks:", marks) 
# print("New Marks:", new_marks)





In [1]:
import numpy as np

mark = np.array([88,90,30,45,75])

mark = mark + 5
print(mark)

[93 95 35 50 80]


In [8]:
mark>45

array([ True,  True, False,  True,  True])

In [ ]:
marks=mark-5
marks/2
print(marks)

In [10]:
marks=mark-5
marks/2
print(marks)

[88 90 30 45 75]


In [9]:
import numpy as np
marks = np.array([88,72,89,91,67])
marks=marks+5

In [5]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [11]:
marks/2


array([44. , 45. , 15. , 22.5, 37.5])

In [12]:
print(marks[0])
print(marks[3])
print(marks[-1])

88
45
75


In [14]:
for i in range (4):
 print(marks[i])

88
90
30
45


In [16]:
marks[:2]
marks[1:4]

array([90, 30, 45])

rows and column

In [18]:
marks=np.array([
    [85,78,90],
    [92,85,98],
    [76,83,67]]
    )

In [19]:
print(marks)

[[85 78 90]
 [92 85 98]
 [76 83 67]]


In [ ]:
marks[0,1]

np.int64(78)

In [23]:
marks[0:2]

array([[85, 78, 90],
       [92, 85, 98]])

In [24]:
marks[0][2]

np.int64(90)

In [ ]:
marks[0:2]         #slicing index
marks[0:2][0:2]     #indexing syntax

array([[85, 78, 90],
       [92, 85, 98]])

In [ ]:
print(marks[1:,0])
#[92,76]
print(marks[1:][0])

#marks[1:]
#[[92 85 98]
#[76 82 80]]

#marks[1:][0]
# [92 85 98]

[92 76]
[92 85 98]


In [30]:
marks[0][0:2]



array([85, 78])

In [38]:
b1=np.array([56,78,89])
b2=np.array([65,76,98])

comb=np.concatenate((b1,b2))
comb 

array([56, 78, 89, 65, 76, 98])

a combined dataset contains six students.The academic team wants to divide the data into two groups for seperate processing.

In [35]:
print(np.split(comb,2))

for arr in np.split(comb,2):
 print(arr)

[array([56, 78, 89]), array([65, 76, 98])]
[56 78 89]
[65 76 98]


In [40]:
mark=np.array([[85,78,90],
      [92,85,98],
      [76,82,80]])
print(np.where(mark==78))
print(mark)

(array([0]), array([1]))
[[85 78 90]
 [92 85 98]
 [76 82 80]]


In [42]:
mark=np.array([[85,78,90],
      [92,85,98],
      [76,82,80]])
print(np.where(mark>=80))
print(mark)

(array([0, 0, 1, 1, 1, 2, 2]), array([0, 2, 0, 1, 2, 1, 2]))
[[85 78 90]
 [92 85 98]
 [76 82 80]]


In [43]:
mark=np.array([[85,78,90],
      [92,85,98],
      [76,82,80]])
print(mark[np.where(mark>=78)])
print(mark)

[85 78 90 92 85 98 82 80]
[[85 78 90]
 [92 85 98]
 [76 82 80]]


In [44]:
np.sort(marks)

array([[78, 85, 90],
       [85, 92, 98],
       [67, 76, 83]])

In [45]:
np.sort(marks)[::-1]

array([[67, 76, 83],
       [85, 92, 98],
       [78, 85, 90]])

In [46]:
np.sort(mark,axis=1)

array([[78, 85, 90],
       [85, 92, 98],
       [76, 80, 82]])

In [47]:
np.sort(mark,axis=0)

array([[76, 78, 80],
       [85, 82, 90],
       [92, 85, 98]])

In [2]:
np.array(['Ram','45'])

array(['Ram', '45'], dtype='<U3')

In [4]:
np.array([45,54,6.5,True])

array([45. , 54. ,  6.5,  1. ])